
com:
  mqtt:

    host: tcp://192.168.126.88:18830
    clientid: JavaSample
    topic: demo/topics
    timeout: 10
    keepalive: 20
    maxReconnectTimes: 5
    reconnInterval: 1
    prefixUrl: http://192.168.126.88:18830

server:
  port: 9090
